name: deploy
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - uses: jetli/trunk-action@v0.5.1
      - uses: Swatinem/rust-cache@v2
      - run: trunk build --release
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true
